### ISSUE TITLE
Admin notes - undefined keyword

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Scripts-X#13]
Hi, there is some error warning while deleting Admin notes from account.
Everything seems like works, but the erros will always print.

https://pastebin.com/1GEt6SME

![image](https://user-images.githubusercontent.com/25097484/210180815-99edf449-d81b-4a2c-b187-53c10635f3ce.png)

**Comment by drk84** [comment]
the OBJ keyword is super outdated!

**Comment by AtillaG1** [comment]
ye seems like changing it to ref1 helps 😘
