### ISSUE TITLE
Why ?

### ISSUE THREAD

**Issue by xMirroRx** [Sphereserver/Scripts-X#19]
![image](https://user-images.githubusercontent.com/10285831/214365739-a0caf137-3aea-48b3-9744-ed9691b2507d.png)

Why do I have to use notepadd or a similar program for all documents like this?

**Comment by Jhobean** [comment]
I recommand visual code or for sexond choice notepad++

Ita not an issue....

**Comment by xMirroRx** [comment]
![image](https://user-images.githubusercontent.com/10285831/214426285-baa3a047-8f96-48d0-93d0-5708f52e21fd.png)
I know it's not a problem, but it's very annoying that it's like this even when you go to the error given in the console.
Typing your commands like this kills the console feature.

**Comment by drk84** [comment]
It's a problem from your side, not from sphere or the scriptpacks

**Comment by Jhobean** [comment]
Its depending on your windows setting how to open a .scp file. On my side it ipen on visual code.

**Comment by cbnolok** [comment]
Probably the newline encoding in that file, Unix instead of windows style, depends on the editor previously used
